"""Static HTML report rendering for `--html` on a couple of commands.

Plain f-strings, no templating engine — matches the project's existing
"keep the dependency footprint minimal" pattern (see jsonl_store.py). The
point of this isn't a dashboard: it's letting trailant's own real output be
screenshotted/embedded somewhere (a README, a write-up, a demo) instead of
someone hand-mocking what the tool "would" show.
"""
from __future__ import annotations

import html as _html
from typing import Optional

from .utils import human_size

_STYLE = """
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 56px 48px;
    background: #0b0f14;
    color: #e8e6df;
    font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  }
  .header { display: flex; align-items: center; gap: 10px; margin-bottom: 28px; }
  .ant { font-size: 26px; }
  .brand { font-size: 20px; font-weight: 700; }
  .tag { color: #7fd8d0; font-size: 13px; margin-left: auto; letter-spacing: .03em; }
  .card { background: #11161d; border: 1px solid #1e2530; border-radius: 12px;
          padding: 32px; max-width: 720px; }
  .card h1 { font-size: 13px; color: #6b7480; font-weight: 600; margin: 0 0 20px;
             text-transform: uppercase; letter-spacing: .06em; }
  .session { padding: 14px 0; border-bottom: 1px solid #1e2530; }
  .session:last-child { border-bottom: none; }
  .source { color: #ff9d5c; font-weight: 600; font-size: 13px; }
  .title { color: #e8e6df; margin-top: 2px; }
  .meta { color: #6b7480; font-size: 12px; margin-top: 6px; }
  .bar-row { display: flex; align-items: center; gap: 12px; padding: 5px 0; }
  .bar-label { width: 82px; color: #6b7480; font-size: 12px; flex-shrink: 0; }
  .bar-track { flex: 1; background: #1e2530; border-radius: 4px; height: 10px; overflow: hidden; }
  .bar-fill { height: 100%; background: #7fd8d0; }
  .bar-count { width: 22px; text-align: right; color: #e8e6df; font-size: 12px; flex-shrink: 0; }
  .summary { margin-top: 18px; color: #9aa2ad; font-size: 13px; line-height: 1.6; }
  .footer { margin-top: 20px; color: #4a5260; font-size: 11px; max-width: 720px; }
"""


def _shell(title: str, tag: str, body: str, footer: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>trailant — {_html.escape(title)}</title>
<style>{_STYLE}</style>
</head>
<body>
  <div class="header">
    <span class="ant">\U0001F41C</span><span class="brand">trailant</span>
    <span class="tag">{_html.escape(tag)}</span>
  </div>
  <div class="card">
    <h1>{_html.escape(title)}</h1>
    {body}
  </div>
  <div class="footer">{_html.escape(footer)}</div>
</body>
</html>
"""


def render_resume_html(trails: list[dict]) -> str:
    rows = []
    for s in trails:
        title = s.get("ai_title") or "(untitled)"
        source = _html.escape(s.get("source", ""))
        project = _html.escape(s.get("project") or "")
        size = _html.escape(human_size(s.get("size_bytes", 0)))
        rows.append(
            f'\n    <div class="session">'
            f'\n      <div class="source">[{source}]</div>'
            f'\n      <div class="title">{_html.escape(title)}</div>'
            f'\n      <div class="meta">{project} · {s.get("prompt_count", 0)} prompts · {size}</div>'
            f'\n    </div>'
        )
    body = "\n".join(rows) if rows else '<div class="summary">No sessions indexed yet.</div>'
    return _shell(
        title="resume — recent sessions across every vendor",
        tag="local-first · no cloud",
        body=body,
        footer="Generated by `trailant resume --html` — reconstructed from local "
               "session trails, nothing sent anywhere.",
    )


def render_cadence_html(weeks_sorted: list[str], counts: dict, avg: float,
                         valley_note: Optional[str]) -> str:
    max_count = max((counts[w] for w in weeks_sorted), default=1) or 1
    rows = []
    for w in weeks_sorted:
        c = counts[w]
        pct = round(c / max_count * 100)
        rows.append(
            f'\n    <div class="bar-row">'
            f'\n      <div class="bar-label">{_html.escape(w)}</div>'
            f'\n      <div class="bar-track"><div class="bar-fill" style="width:{pct}%"></div></div>'
            f'\n      <div class="bar-count">{c}</div>'
            f'\n    </div>'
        )
    note = _html.escape(valley_note) if valley_note else "No valley currently flagged in this window."
    body = "\n".join(rows) + f'\n    <div class="summary">Average: {avg:.1f} sessions/week<br>{note}</div>'
    return _shell(
        title=f"cadence — last {len(weeks_sorted)} weeks",
        tag="your own baseline, not anyone else's",
        body=body,
        footer="Generated by `trailant cadence --html` — reconstructed from local "
               "session trails, nothing sent anywhere.",
    )
