from trailant.utils import is_system_wrapper_text


def test_known_wrapper_tag_is_detected():
    text = (
        "<local-command-caveat>Caveat: the messages below were generated by "
        "the user while running local commands.</local-command-caveat>"
    )
    assert is_system_wrapper_text(text) is True


def test_real_prompt_is_not_flagged():
    assert is_system_wrapper_text("fix the retry logic in the ingest job") is False


def test_unknown_leading_tag_is_not_flagged():
    # A real message that happens to start with "<" but isn't one of the
    # known vendor-injected wrapper tags should not be treated as one.
    assert is_system_wrapper_text("<script> isn't valid here, is it?") is False


def test_empty_text_is_not_flagged():
    assert is_system_wrapper_text("") is False


def test_environment_context_tag_is_detected():
    assert is_system_wrapper_text("<environment_context>cwd: /home/me</environment_context>") is True


def test_agents_md_prefix_is_detected():
    # Confirmed verbatim from a real Windows session's generated HTML output.
    assert is_system_wrapper_text("# AGENTS.md instructions\n\nFollow these rules...") is True
