from trailant.utils import is_system_wrapper_text, looks_like_secret


def test_known_wrapper_tag_is_detected():
    text = (
        "<local-command-caveat>Caveat: the messages below were generated by "
        "the user while running local commands.</local-command-caveat>"
    )
    assert is_system_wrapper_text(text) is True


def test_real_prompt_is_not_flagged():
    assert is_system_wrapper_text("fix the retry logic in the ingest job") is False


def test_unknown_leading_tag_is_not_flagged():
    # A real message that happens to start with "<" but isn't one of the
    # known vendor-injected wrapper tags should not be treated as one.
    assert is_system_wrapper_text("<script> isn't valid here, is it?") is False


def test_empty_text_is_not_flagged():
    assert is_system_wrapper_text("") is False


def test_environment_context_tag_is_detected():
    assert is_system_wrapper_text("<environment_context>cwd: /home/me</environment_context>") is True


def test_agents_md_prefix_is_detected():
    # Confirmed verbatim from a real Windows session's generated HTML output.
    assert is_system_wrapper_text("# AGENTS.md instructions\n\nFollow these rules...") is True


def test_ide_opened_file_tag_is_detected():
    # Found via a benchmark against real data: a 209MB session's title
    # surfaced as this wrapper instead of a real prompt.
    assert is_system_wrapper_text("<ide_opened_file>The user opened the file /a/b.py</ide_opened_file>") is True


def test_looks_like_secret_detects_password_assignment():
    assert looks_like_secret("the prod db password=hunter2 stopped working") is True


def test_looks_like_secret_detects_api_key():
    assert looks_like_secret("set STRIPE_API_KEY=sk_live_abc123") is True


def test_looks_like_secret_detects_bearer_token():
    assert looks_like_secret("curl -H 'Authorization: Bearer abcdef0123456789'") is True


def test_looks_like_secret_detects_aws_access_key():
    assert looks_like_secret("AKIAABCDEFGHIJKLMNOP leaked in the log") is True


def test_looks_like_secret_detects_private_key_header():
    assert looks_like_secret("-----BEGIN RSA PRIVATE KEY-----") is True


def test_looks_like_secret_ignores_ordinary_text():
    assert looks_like_secret("fix the retry logic in the ingest job") is False


def test_looks_like_secret_ignores_the_word_secret_alone():
    # "secret" mentioned without an assignment shouldn't fire — avoid
    # alarm fatigue on ordinary conversation about secrets management.
    assert looks_like_secret("we should rotate our secrets more often") is False


def test_looks_like_secret_handles_empty_text():
    assert looks_like_secret("") is False
